services:
  - type: web
    name: patient-management-api
    runtime: node
    rootDir: server
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        value: patient_secret_key
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: admin12345
